export { EditorView, highlightSpecialChars, drawSelection, dropCursor, highlightActiveLine, keymap, ViewPlugin } from "@codemirror/view";
export { EditorState, Annotation, StateField } from "@codemirror/state";
export { history, historyKeymap, undoSelection, redoSelection } from "@codemirror/history";
export { foldGutter, foldKeymap } from "@codemirror/fold";
export { indentOnInput } from "@codemirror/language";
export { lineNumbers, highlightActiveLineGutter } from "@codemirror/gutter";
export { defaultKeymap, indentWithTab} from "@codemirror/commands";
export { bracketMatching } from "@codemirror/matchbrackets";
export { closeBrackets, closeBracketsKeymap } from "@codemirror/closebrackets";
export { highlightSelectionMatches, searchKeymap, openSearchPanel, closeSearchPanel, findNext, findPrevious, replaceNext, replaceAll, searchConfig, SearchQuery, setSearchQuery, getSearchQuery } from "@codemirror/search";
export { autocompletion, completionKeymap, completeAnyWord, completeFromList, ifNotIn } from "@codemirror/autocomplete";
export { commentKeymap } from "@codemirror/comment";
export { rectangularSelection } from "@codemirror/rectangular-selection";
export { defaultHighlightStyle, HighlightStyle, tags } from "@codemirror/highlight";
export { lintKeymap } from "@codemirror/lint";
export { panels } from "@codemirror/panel";
export { hoverTooltip, showTooltip } from "@codemirror/tooltip";

export { htmlLanguage, htmlCompletion, html } from "@codemirror/lang-html";
export { cssLanguage, cssCompletion, css } from "@codemirror/lang-css";
export { javascriptLanguage, typescriptLanguage, javascript } from "@codemirror/lang-javascript";
export { jsonLanguage, json } from "@codemirror/lang-json";
export { javaLanguage, java } from "@codemirror/lang-java";
export { cppLanguage, cpp } from "@codemirror/lang-cpp";
export { rustLanguage, rust } from "@codemirror/lang-rust";
export { phpLanguage, php } from "@codemirror/lang-php";
